export const OXFORD_DATA = [
  { eng: "Ability", tr: "Yetenek", ex: "She has the ___ to pass.", opts: ["ability", "apple", "adult", "account"] },
  { eng: "Accept", tr: "Kabul etmek", ex: "I ___ your gift.", opts: ["accept", "advice", "agree", "avoid"] },
  { eng: "Accurate", tr: "Doğru", ex: "This map is ___.", opts: ["accurate", "active", "angry", "actual"] },
  { eng: "Benefit", tr: "Fayda", ex: "The new law will ___ everyone.", opts: ["benefit", "believe", "beyond", "bottom"] },
  { eng: "Challenge", tr: "Meydan okuma", ex: "This is a real ___.", opts: ["challenge", "change", "chance", "charge"] },
  { eng: "Deadline", tr: "Son teslim tarihi", ex: "The ___ is tomorrow.", opts: ["deadline", "decision", "decrease", "defense"] },
  { eng: "Efficient", tr: "Verimli", ex: "We need an ___ system.", opts: ["efficient", "election", "element", "emergency"] },
  { eng: "Flexible", tr: "Esnek", ex: "My schedule is ___.", opts: ["flexible", "favorite", "festival", "frequent"] },
  { eng: "Guarantee", tr: "Garanti", ex: "I ___ your safety.", opts: ["guarantee", "general", "garden", "growth"] },
  { eng: "Healthy", tr: "Sağlıklı", ex: "I want to lead a ___ life.", opts: ["healthy", "history", "happen", "heavy"] },
  { eng: "Imagine", tr: "Hayal etmek", ex: "___ a world without war.", opts: ["imagine", "improve", "important", "include"] },
  { eng: "Journey", tr: "Yolculuk", ex: "Have a safe ___!", opts: ["journey", "justice", "jacket", "judge"] },
  { eng: "Knowledge", tr: "Bilgi", ex: "He has a lot of ___.", opts: ["knowledge", "kitchen", "keyboard", "king"] },
  { eng: "Language", tr: "Dil", ex: "English is a global ___.", opts: ["language", "laugh", "lawyer", "leader"] },
  { eng: "Message", tr: "Mesaj", ex: "I received a ___.", opts: ["message", "memory", "member", "method"] },
  { eng: "Necessary", tr: "Gerekli", ex: "Is it ___ to wait?", opts: ["necessary", "negative", "network", "nature"] },
  { eng: "Opposite", tr: "Zıt", ex: "Hot is the ___ of cold.", opts: ["opposite", "opinion", "opening", "order"] },
  { eng: "Patient", tr: "Sabırlı", ex: "Please be ___.", opts: ["patient", "pattern", "partner", "payment"] },
  { eng: "Quality", tr: "Kalite", ex: "This is high ___.", opts: ["quality", "quarter", "question", "quickly"] },
  { eng: "Remember", tr: "Hatırlamak", ex: "I can't ___ her name.", opts: ["remember", "receive", "reduce", "remove"] },
  { eng: "Situation", tr: "Durum", ex: "The ___ is serious.", opts: ["situation", "science", "section", "service"] },
  { eng: "Together", tr: "Birlikte", ex: "Let's study ___.", opts: ["together", "tomorrow", "tonight", "towards"] },
  { eng: "Upgrade", tr: "Yükseltmek", ex: "Time to ___ your phone.", opts: ["upgrade", "urgent", "useful", "usually"] },
  { eng: "Valuable", tr: "Değerli", ex: "Time is ___.", opts: ["valuable", "various", "village", "visit"] },
  { eng: "Wonderful", tr: "Harika", ex: "What a ___ day!", opts: ["wonderful", "weather", "wedding", "welcome"] }
];
